[program:organizando-fotos]
directory=/var/www/organizando-fotos
command=/var/www/organizando-fotos/venv/bin/gunicorn --workers 2 --bind 127.0.0.1:5000 run:app
user=organizador
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/organizando-fotos/logs/gunicorn.log
environment=FLASK_ENV=production,DATABASE_PATH=/var/www/organizando-fotos/data/multimedia.db